#use_frameworks!

platform :ios, '8.0'

target 'ZZVerticalMarqueeView_Example' do
  pod 'ZZVerticalMarqueeView', :path => '../'

  target 'ZZVerticalMarqueeView_Tests' do
    inherit! :search_paths

    
  end
end
